---
- hosts: nginx001
  tasks:
    - name: Install epel repo
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Add nginx virtualhost config
      template:
        src: nginx_tpl/itbm.com.conf
        dest: /etc/nginx/conf.d/itbm.com.conf

    - name: Check nginx configs
      shell: "/usr/sbin/nginx -t"
      register: nginx_config_status

    - name: nginx test status
      debug:
        msg: "{{ nginx_config_status }}"
    
    - name: Create dir
      file:
        path: /var/www/itbm.com
        mode: 0755
        state: directory

    - name: Copy index file for test
      copy:
        src: nginx_tpl/index.html
        dest: /var/www/itbm.com

   - name: Service nginx restart and enable on boot
      systemd:
        name: nginx
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: nginx_config_status.rc == 0
