---
- hosts: nginx001
  tasks:
    - name: Install epel repo
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: latest
    
    - name: Create dir
      file:
        path: /var/www/itbm.com
        mode: 0755
        state: directory

    - name: Add nginx virtualhost config
      template:
        src: itbm.com.conf.j2
        owner: nginx
        group: nginx
        mode: 0644
        dest: /etc/nginx/conf.d/itbm.com.conf

    - name: Check nginx configs
      shell: "/usr/sbin/nginx -t"
      register: nginx_config_status

    - name: nginx test status
      debug:
        msg: "{{ nginx_config_status }}"
    
    - name: Add index template for test
      template:
        src: index.html.j2
        dest: /var/www/itbm.com/index.html
  
    - name: Service nginx restart and enable on boot
      systemd:
        name: nginx
        state: restarted
        enabled: yes
        daemon_reload: yes
    
    # Change firewall zone

    - name: Set active zone
      firewalld:
        zone: trusted
        interface: eth0
        state: enabled
        immediate: yes
        permanent: true

